### ISSUE TITLE
ifm_sentinel.gammaProcess creates unused xml and log files

### ISSUE THREAD

**Issue by asjohnston-asf** [ASFHyP3/hyp3-insar-gamma#73]
https://github.com/ASFHyP3/hyp3-insar-gamma/blob/develop/hyp3_insar_gamma/ifm_sentinel.py#L361-L379

I think it's possible everything here can go, other than os.chdir(wrk). I don't see us including any xml, metadata, or log files in the output package other than the readme. The hdf5/xsltproc business mirrors the old workflow in hyp3-rtc-gamma for building the .iso.xml file; hdf5.txt would have been passed to the MapReady write_hdf5_xml command.

If that's the case, we can also drop `etc/sentinel_xml.xsl`, as well as `xsltproc` from the Dockerfile.

**Comment by jhkennedy** [comment]
Done in #77
